/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "nyqfsuwxrzrfnrslpgfj"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55cWZzdXd4cnpyZm5yc2xwZ2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0NjYxMjUsImV4cCI6MjA4NzA0MjEyNX0.WqIJVzzjcVE-ZtxGFoIXqIMTZNeJzTlk8NB9pl-HIjI"